src/Pickl/AppBundle/Entity/Image.php
<?php

namespace Pickl\AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="Pickl\AppBundle\Repository\ImageRepository")
 * @Vich\Uploadable
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @Vich\UploadableField(mapping="project_image", fileNameProperty="url")
     * @Assert\Image(maxSize="1M")
     * @Assert\NotBlank()
     */
    private $file;

    /**
     * @ORM\Column(name="update_at", type="datetime", nullable=true)
     */
    private $updateAt;

    /**
     * Champ caché pour les formulaires
     */
    private $hiddenUrl = null;

    public function getHiddenUrl() {
        return $this->hiddenUrl;
    }

    public function setHiddenUrl($hiddenUrl) {
        $this->hiddenUrl = $hiddenUrl;
        return $this;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile(File $image = null)
    {
        $this->file = $image;

        if($image) {
            $this->updateAt = new \DateTime('now');
        }

        return $this;
    }

    /**
     * Set updateAt
     *
     * @param \DateTime $updateAt
     *
     * @return Image
     */
    public function setUpdateAt($updateAt)
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    /**
     * Get updateAt
     *
     * @return \DateTime
     */
    public function getUpdateAt()
    {
        return $this->updateAt;
    }

    public function getUploadDir()
    {
        return 'uploads/img';
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getUrl();
    }

    public function getCatWebPath()
    {
        return 'assets/img/category/'.$this->getUrl();
    }

    public function getRewardWebPath()
    {
        return 'assets/img/reward/'.$this->getUrl();
    }
}

src/Pickl/AppBundle/Controller/MainController.php
<?php

namespace Pickl\AppBundle\Controller;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\HttpFoundation\Request;
use Pickl\AppBundle\Entity\Newsletter;

class MainController extends Controller implements TokenAuthenticatedController  {

    // HOME PAGE
    public function indexAction() {

        $em = $this->getDoctrine()->getManager();
        $categories = $em->getRepository('PicklAppBundle:Category')->findAll();
        $projects = $em->getRepository('PicklAppBundle:Project')->findThreeLast();

        $ofTheDay = $this->container->get('pickl_app.of_the_day');

        $response = $ofTheDay->getProjectOfTheDayAndTrends();

        // on fait le rendu
        // trends contient 3 arrays associatifs avec sum et entity (projects)
        // ofTheDay contient 1 array associatif avec sum et entity (project
        return $this->render(
            'PicklAppBundle:Main:index.html.twig',
            array(
                'ofTheDay' => $response['ofTheDay'],
                'trends' => $response['trends'],
                'categories' => $categories,
                'projects' => $projects
            )
        );
    }

    // SEARCH PAGE
    public function searchAction(Request $request) {
        $arg = strtolower($request->query->get('q'));

        if(empty($arg))
            throw new Exception('Please type something before submit');

        $em = $this->getDoctrine()->getManager();
        $projectRepository = $em->getRepository('PicklAppBundle:Project');

        // on recup les projets qui contiennent l'arg en titre, smallDesc ou bigDesc, tags
        $projects = $projectRepository->searchWithArg($arg);

        $picklSearch = $this->container->get('pickl_app.search');

        // on organise les résultats
        $results = $picklSearch->organizeSearch($projects, $arg);

        return $this->render(
            'PicklAppBundle:Main:search.html.twig',
            array(
                'arg' => $arg,
                'results' => $results
            )
        );
    }

    // RANKING PAGE
    public function getRankingAction($limit) {
        $limit = (int) $limit;

        if($limit < 1)
            throw new NotFoundHttpException('Limit "'.$limit.'" too small');

        $em = $this->getDoctrine()->getManager();

        $users = $em
            ->getRepository('PicklAppBundle:User')
            ->findAllUsersOrderByXp()
        ;

        $tabUsers = array();
        $i = 1;
        $placeCurrentUser = false;
        foreach($users as $user) {
            if($this->getUser() !== null) {
                if($this->getUser()->getUsername() == $user->getUsername()) {
                    $placeCurrentUser = $i;
                }
            }

            $tabUsers[] = array(
                'place' => $i,
                'user' => $user
            );
            $i++;
        }

        $tabFinal = array();
        for($i = 0; $i<$limit;$i++) {
            if(isset($tabUsers[$i]))
                $tabFinal[] = $tabUsers[$i];
        }

        return $this->render(
            'PicklAppBundle:Main:ranking.html.twig',
            array(
                'users' => $tabFinal,
                'limit' => $limit,
                'placeCurrentUser' => $placeCurrentUser
            )
        );
    }


    public function getRewardsAction()
    {
        $em = $this->getDoctrine()->getManager();

        $rewards = $em->getRepository('PicklAppBundle:Reward')->findAll();

        $projects = $em->getRepository('PicklAppBundle:Project')->findAll();
        $nbComments = count($em->getRepository('PicklAppBundle:Comment')->findAll());

        $total = 0;
        $highestPercentage = 0;
        foreach($projects as $project) {
            $total += $project->getCollectedAmount();
            if($project->getPercent() > $highestPercentage)
                $highestPercentage = $project->getPercent();
        }

        $nbProjects = count($projects);
        $highestPercentage = (int) $highestPercentage;

        return $this->render(
            'PicklAppBundle:Main:rewards.html.twig',
            array(
                'nbProjects' => $nbProjects,
                'nbComments' => $nbComments,
                'bestPercentage' => $highestPercentage,
                'totalAmount' => $total,
                'rewards' => $rewards
            )
        );
    }


    // EXPLORE PAGE
    public function exploreAction($limit) {
        $limit = (int) $limit;

        // get categories
        // get project of the day
        // get all project avec limit
        $em = $this->getDoctrine()->getManager();

        $categories = $em->getRepository('PicklAppBundle:Category')->findAll();

        // project of the day
        $ofTheDay = $this->container->get('pickl_app.of_the_day');
        $projectOfTheDay = $ofTheDay->getProjectOfTheDayAndTrends()['ofTheDay'];

        // all projects with limit order by date desc
        $projects = $em->getRepository('PicklAppBundle:Project')->findAllProjectsWithLimit($limit);


        return $this->render(
            'PicklAppBundle:Main:explore.html.twig',
            array(
                'limit' => $limit,
                'categories' => $categories,
                'ofTheDay' => $projectOfTheDay,
                'projects' => $projects
            )
        );
    }

    // HOW IT WORKS
    public function getHowItWorksAction(){
        return $this->render(
            'PicklAppBundle:Main:howitworks.html.twig'
        );
    }

    public function newsletterAction(Request $request) {

        $referer = $request->headers->get('referer');

        $mail = $request->request->get('mail');

        if((empty($mail)))
            return $this->redirectToRoute('pickl_app_homepage');

        $em = $this->getDoctrine()->getManager();
        $found = $em->getRepository('PicklAppBundle:Newsletter')->findWithMail($mail);

        if($found === null) {
            // rien n'est en BDD, on peut ajouter
            $user = new Newsletter();
            $user->setMail($mail);

            $em->persist($user);
            $em->flush();

            $request->getSession()->getFlashBag()->add('info','Thanks! "'.$mail.'" added to newsletter');

        } else {
            $request->getSession()->getFlashBag()->add('info','Email "'.$mail.'" already registered !');
        }

        if(!empty($referer)) {
            return $this->redirect($referer);
        } else {
            return $this->redirectToRoute('pickl_app_homepage');
        }
    }

    public function getAboutAction() {
        return $this->render(
            'PicklAppBundle:Main:about.html.twig'
        );
    }

}

src/Pickl/AppBundle/Resources/views/Main/about.html.twig
{% extends "PicklAppBundle::layout.html.twig" %}

{% block title %}{{ parent() }} – About{% endblock %}

{% block body %}

<div id="topabout" class="top">
    <div class="containtoptitle">
        <h1>ABOUT US</h1><br>
        <p>Learn more about our team.</p>
    </div>
</div>
<div id="content" class="howitcontent">
    <div id="aboutcontent">

        <div class="articleparagraphcenter">
            <h2>OUR STORY</h2>
            <p>
                Pickl is born in 2009 in South Africa and more precisely in his capital city, Johannesburg,
                from the idea of Graeme Smith and his associate Jan van Riebeeck. At its beginnings, the
                team was only composed of 12 peoples, mainly developers and designers. The team name
                was then Flamingo.
            </p>
            <p>
                So many things happened since then! We now have offices in New York, Milan, Berlin and
                Stockholm and we count more than 125 employees.
            </p>
            <p>
                We still try to improve your experience on Pickl by working hard every day since the
                beginning, on each aspect of the site. We are all passionate and 100% invested in our tasks.
            </p>
        </div>

        <div id="teamcontainer">
            <div id="teamtitle"><h2>HOW IT WORKS<br>FAQ</h2></div>
            <div id="teambloccontainer">
                <div class="teambloc">
                    <span>PROJECT CREATOR'S OPINION</span>
                    <div class="teamimg"><img src="{{ asset('assets/img/team1.jpg') }}"/></div>
                    <p>“Pickl is revolutionizing traditional crowdfunding methods by offering the opportunity to
                        present your project to the public directly, which actually makes you the real master of it”.</p>
                    <quote>John Doe</quote>
                </div><!--
                --><div class="teambloc blocright">
                    <span>CONTRIBUTOR'S OPINION</span>
                    <div class="teamimg"><img src="{{ asset('assets/img/team2.jpg') }}"/></div>
                    <p>“I have contributed to more than 30 projects throughout the different categories on Pickl and
                        I have never have been disappointed by any of these projects. I really feel invested when I
                        contribute.”</p>
                    <quote>Jane Doe</quote>
                </div>
            </div>
        </div>


        <div class="articleparagraph">
            <h2>OUR TEAM</h2>
            <p>Since our beginnings, we have constantly evolved, by setting up offices in many cities of the
                world. We are now a big family, composed of 125 employees from all around the world. We
                enjoy to support you, giving life to your ideas.</p>
            <p>
                In Pickl, we have many roles: developers, graphic designers, lawyers, community managers
                etc.
            </p>
            <p>
                We know that, if we are here today, it is thanks to you. We wouldn’t be what we are without
                your incredible contributions. Thanks to you and we are happy to have you with us in this
                wonderful community.
            </p>
        </div>
        <div class="aboutimg">
        </div>

        <div class="articleparagraph">
            <h2>PICKL IN FEW NUMBERS</h2>
        </div>

        <div class="bignumber">
            <div class="pairnumber">
                <div class="numbercontent"><h3><strong>700 000</strong><br>VISITORS EACH DAY</h3></div><!--
                    --><div class="numbercontent"><h3><strong>68%</strong><br>OF PROJECTS REACH THEIR GOAL</h3></div>
            </div>
            <div class="pairnumber">
                <div class="numbercontent"><h3><strong>14 MINUTES</strong><br>THE FASTEST FINANCED PROJECT</h3></div><!--
                    --><div class="numbercontent"><h3><strong>3 WEEKS</strong><br>OF DEVELOPMENT FOR PICKL</h3></div>
            </div>
        </div>

    </div>
{% endblock %}

src/Pickl/AppBundle/Resources/views/Main/explore.html.twig
{% extends 'PicklAppBundle::layout.html.twig' %}
{% block title %}{{ parent() }} – Explore{% endblock %}
{% block topproject %}
    <div id="topproject" class="top" style="background:url('{{ asset('assets/img/explore.jpg') }}') no-repeat center top fixed;background-size:cover;">
    </div>
    <div id="contenttitle">
        <h1>EXPLORE</h1>
    </div>
{% endblock %}
{% block body %}

    <div class="trend" style="padding-left:30px; padding-bottom:30px !important;">
        <h2>ALL PROJECTS //</h2>
        <div class="sep"></div>
    </div>

    {% if projects is empty %}

        <div class="specialInfoCat">
            <h5>No project found :(</h5>
            <a href="{{ path('pickl_app_project_add') }}">Why not create yours now ?</a>
            <a href="{{ path('pickl_app_explore') }}">Let's explore some others amazing projects !</a>
        </div>

    {% else %}

        <table class="contentcat">
            <tr style="height:0 !important;"><td></td><td></td><td></td></tr>
            <tr>
            {% for project in projects %}
                {% if loop.index0 is divisible by(3) %}
                    </tr><tr>
                {% endif %}
                <td style="width:33% !important; padding-bottom:150px !important;">
                    <div class="catImg" style="background:url({{ asset(project.picture.getWebPath) }}) no-repeat center;background-size: cover;">
                        <a href="{{ path('pickl_app_project_view', {'slug':project.slug}) }}"></a>
                    </div>
                    <div class="catContent">
                        <h3>
                            <a href="{{ path('pickl_app_project_view', {'slug':project.slug}) }}">
                                {{ project.title }}
                            </a>
                        </h3>
                        <quote>#{{ project.category.name }}</quote>
                        <div class="catSmallDesc">{{ project.smallDescription|slice(0,80) }}...</div>
                        <div class="percentBar">{{ project.percent }}%</div>
                        <div class="goalbar"><div class="goalbarload" style="width:{{ project.percent }}%;max-width:100%;"></div></div>
                        <div class="percentBar">{{ project.remainingTime }} left</div>
                    </div>
                </td>
            {% endfor %}
        </table>

        <div id="loadmorenews" style="margin-bottom:100px;"><p><a href="{{ path('pickl_app_explore', {'limit':(limit+10)}) }}">+</a></p></div>

    {% endif %}
{% endblock %}

src/Pickl/AppBundle/Resources/views/Main/howitworks.html.twig
{% extends "PicklAppBundle::layout.html.twig" %}

{% block title %}{{ parent() }} – How it works{% endblock %}

{% block body %}
   
   
   <div id="tophow" class="top">
   <div class="containtoptitle">
       <h1>HOW IT WORKS</h1><br>
   <p>The way of creating a project successfully</p>
   </div>
   </div>
   <div id="content" class="howitcontent">
   <div id="howitbackground">
   
   <div class="articleparagraph">
           <h2>1. IMAGINE</h2>
           <img src="{{ asset('assets/icon/imagine.png') }}"/>
            <p>Once the sketch of your project is realized, it is up to you to fix the limits and to define context and goals. The audience, which you need to quickly arouse interest, must feel involved. For this, you must awake his curiosity and the best way to do this is to talk about it all around you, whether in the street or on social networks and even within the community of Pickl.

                <br><br>
                Now, what you have to do is to:
                <br>-	Tell the story of your project and write description and objectives,
                <br>-	Insert illustrations and sketches to show that your project is concrete,
                <br>-	Essential step, establish a budget to reach to make the project achievable,
                <br>-	Define gifts, kinds of rewards given to Picklr that contribute to your project,
                <br>-	Do not forget to publish your project to show it to the world!

                <br><br>And for that, nothing’s easier, simply click on the “Start a campaign” menu and you just have to follow the steps that will guide you from the beginning to the end of the creation of your project.

                Pickl also puts several tools at your disposal to direct you, including a video tutorial.</p>
            </div>
            
            <div class="articleparagraph">
           <h2>2. FINANCE</h2>
           <img src="{{ asset('assets/icon/finance.png') }}"/>
                <p>
                    Funding step is a milestone in the emergence of your project. It is this that will determine
                    whether your project is viable and if it will come out. Stand out to maximize your chances to
                    raise the necessary funds previously set! Be original and above all, you need to stay active.
                </p>
                <p>
                    It is imperative to keep Picklr in breath of: what is happening in parallel of the progression of the financing, the way you perceive feedbacks and how the project evolves. It is therefore important to write news regularly.
                    Do not neglect promotion. It also holds an important place in the outcome of the project. Mobilize even more those who already supports you by encouraging them to talk about it to their relatives.
                </p>
                <p>
                    Do not neglect promotion. It also holds an important place in the outcome of the project.
                    Mobilize even more those who already supports you by encouraging them to talk about it to
                    their relatives.
                </p>
            </div>
            
            <div class="articleparagraph">
           <h2>3. BUILD</h2>
           <img src="{{ asset('assets/icon/build.png') }}"/>
            <p>
                The goal is reached! A final task awaits you, but not least, since it is the conception itself of
                your project. It is from that time that your project actually becomes concrete and you can
                finally touch it for real.
            </p>
            <p>
                Now that Pickl provided all the necessary tools for the success of your project, the
                completion of the final stage only depends on you!
            </p>
            </div>
            
            <div class="articleparagraph">
           <h2>4. DELIVER!</h2>
           <img src="{{ asset('assets/icon/deliver.png') }}"/>
                <p>
                    Congratulations! The project that you are working on for several weeks finally see the daylight and henceforth, it only remains to commercialize it. But this not the end of the adventure!
                    Remember those who helped you to get there and it is precisely the aim of the gifts.
                </p>
                <p>
                    The Picklr who took part in your adventure through gifts now expect that you keep your promises.
                    You must present the awards to contributors, without forgetting to thank them.
                </p>
            </div>
       </div>
       
       <div id="howitfaq">
           <div id="howitfaqtitle">
           <h2>FAQ</h2>
       </div>
            
            <div class="articleparagraph">
           <h3>What is Pickl?</h3>
            <p>Pickl is a funding platform that allows anybody to give birth to originals projects.
                Once you created a project, you become part of the creators. But, these projects are funded only if they reach or exceed their goal and this, is based on contributors. They commit money to bring them to life.

                It means that, as a contributor, you’ll be refunded the full amount invested in the case the project doesn’t reach his goal. It is the principle of crowdfunding by Pickl.</p>
            </div>
            
            <div class="articleparagraph">
           <h3>Does it really work?</h3>
            <p>Since his creation, Pickl gave birth to 31 000 innovative and creative projects all around the world, collecting more than 4 million dollars.
            </p>
            </div>
            
            <div class="articleparagraph">
           <h3>What do I have to know before starting any project?</h3>
            <p>Your project must be clear in your head, from the beginning to the end. Plus, you must have the required time to spend on working for it.

                Then, make sure your idea is viable and that it can affect a large range of people to multiply your chance of reaching your goal. If your project is way too specific, you’ll probably have to adapt the amount to reach by reducing it.</p>
            </div>

           <div class="articleparagraph">
               <h3>What do I have to know before contributing?</h3>
               <p>Contributing is pretty simple: in first place, most of these contributors are project creator’s friends while others are motivated by getting an interesting gifts or simply like the idea of the project. So it means a lot. It is not giving away your money. You support an original idea that you want to see exist.</p>
           </div>

           <div class="articleparagraph">
               <h3>What are the gifts?</h3>
               <p>Gifts, that you can see on the right side of a project, enable you to invest a specific amount of money, beforehand defined by the creator, in return of obtaining a gift from the creator at the time of the distribution.</p>
           </div>


       </div>

   
{% endblock %}

src/Pickl/AppBundle/Resources/views/Main/ranking.html.twig
{% extends "PicklAppBundle::layout.html.twig" %}

{% block title %}{{ parent() }} – Users{% endblock %}

{% block body %}
    <div id="content" class="rewardscontent">
    <div id="rewardbackground">
    <div class="articleparagraph">
        <h2>RANKING</h2>
        <img src="{{ asset('assets/img/reward/ranking.png') }}"/>
        <p>
            This ranking table gather the best Picklrs based on the experience they obtained by realizing
            different activities. There are several ways to get experience: creating a project, contributing,
            commenting… And collecting all the rewards!
        </p>
        <p>
            The ranking is refreshed each second with the latest statistics of Pickl so you can see how
            you evolve.
        </p>
    </div>

        <div class="tablestats tableranking">
            <table>
                <tr class="firststats"><td></td><td>PLACE</td><td>USERNAME</td><td>LVL</td><td>XP</td></tr>
    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                <tr style="background-color:rgb(71,154,88);color:white;"><td><div class="profileWrap"><div class="profileInner"><div class="profile" style="background: url({{ asset(app.user.profilePicture.getWebPath) }}) center no-repeat;background-size:cover;"></div></div></div></td><td>#{{ placeCurrentUser }}</td><td><a style="color:white !important;" href="{{ path('pickl_app_user_view', {'username': app.user.username}) }}" alt="{{ app.user.username }}">{{ app.user.username }}</a></td><td>Lvl.{{ app.user.level }}</td><td>{{ app.user.experience }}</td></tr>
    {% endif %}
                {#  Foreach tableau  #}
                {% for user in users %}
                    <tr>
                        <td><div class="profileWrap"><div class="profileInner"><div class="profile" style="background: url({{ asset(user.user.profilePicture.getWebPath) }}) center no-repeat;background-size:cover;"></div></div></div></td>
                        <td>#{{ user.place }}</td>
                        <td><a href="{{ path('pickl_app_user_view', {'username': user.user.username}) }}" alt="{{ user.user.username }}">{{ user.user.username }}</a></td>
                        <td>Lvl.{{ user.user.level }}</td>
                        <td>{{ user.user.experience }}</td>
                    </tr>


                    {% endfor %}

            </table>
            <div id="loadmorenews"><p><a href="{{ path('pickl_app_ranking', {'limit':(limit+25)}) }}">+</a></p></div>
        </div>

    </div>
    </div>
{% endblock %}

src/Pickl/AppBundle/Resources/views/Main/rankingOLD.html.twig
{% extends "PicklAppBundle::layout.html.twig" %}

{% block title %}Users - {{ parent() }}{% endblock %}

{% block body %}
    {% for message in app.session.flashbag.get('info') %}
        <p>Message flash : {{ message }}</p>
    {% endfor %}

    <h1>Ranking</h1>

    {% if is_granted('ROLE_USER') %}
        <div class="well">
            <h2><a href="{{ path('pickl_app_user_view', {'username': app.user.username}) }}" alt="{{ app.user.username }}">{{ app.user.username }}</a></h2>
            <p>{{ app.user.experience }}</p>
            <p>Lvl.{{ app.user.level }}</p>
            <p>{{ app.user.rank.name }}</p>
            <b>{{ app.user.username }}</b>
            <p>{{ app.user.email }}</p>
        </div>
    {% endif %}

    {% for user in users %}
        <div class="well">
            <h2><a href="{{ path('pickl_app_user_view', {'username': user.user.username}) }}" alt="{{ user.user.username }}">{{ user.user.username }}</a></h2>
            <p>{{ user.user.experience }}</p>
            <p>Lvl.{{ user.user.level }}</p>
            <p>{{ user.user.rank.name }}</p>
            <b>{{ user.user.username }}</b>
            <p>{{ user.user.email }}</p>
        </div>
    {% endfor %}

    <a href="{{ path('pickl_app_ranking', {'limit':(limit+25)}) }}">More</a>
{% endblock %}

src/Pickl/AppBundle/Resources/views/Main/rewards.html.twig
{% extends "PicklAppBundle::layout.html.twig" %}

{% block title %}{{ parent() }} – Rewards{% endblock %}

{% block body %}

<div id="content" class="rewardscontent">
    <div id="rewardbackground">

        <div class="articleparagraph">
            <h2>REWARDS</h2>
            <img src="{{ asset('assets/img/reward/rewards.png') }}"/>
            <p>
                The rewards allow you to get experience throughout different activities. Their main utility is to
                help you getting more experience.
            </p>
        </div>

        <div id="logocontainer">
            {% for reward in rewards %}
                <div class="logosolo">
                    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                        {% if app.user.hasReward(reward.id) %}
                            <img src="{{ asset(reward.icon.rewardWebPath) }}"/>
                            <p>{{ reward.name }}</p>
                        {% else %}
                            <img class="rewardLight" src="{{ asset(reward.icon.rewardWebPath) }}"/>
                            <p class="rewardLight">{{ reward.name }}</p>
                        {% endif %}
                    {% else %}
                        <img src="{{ asset(reward.icon.rewardWebPath) }}"/>
                        <p>{{ reward.name }}</p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        <div class="articleparagraph">
            <h2>AWARDS</h2>
            <img src="{{ asset('assets/img/reward/awards.png') }}"/>
            <p>
                The awards are the proof that Pickl and his community can make big things together!
            </p>
        </div>



        <div class="bignumber">
            <div class="pairnumber">
                <div class="numbercontent"><h3><strong>${{ totalAmount }}</strong><br>RECOLTED. THANKS!</h3></div><!--
                    --><div class="numbercontent"><h3><strong>{{ bestPercentage }}%</strong><br>BIGGEST PERCENTAGE</h3></div>
            </div>
            <div class="pairnumber">
                <div class="numbercontent"><h3><strong>{{ nbComments }}</strong><br>COMMENTS POSTED</h3></div><!--
                    --><div class="numbercontent"><h3><strong>{{ nbProjects }}</strong><br>PROJECTS CREATED</h3></div>
            </div>
        </div>

    </div>

    {% endblock %}

src/Pickl/AppBundle/Resources/views/Main/rewardsOLD.html.twig
{{ dump(nbProjects) }}projects
{{ dump(nbComments) }}comments
{{ dump(bestPercentage) }}%
{{ dump(totalAmount) }}&dollar;
{{ dump(rewards) }}